

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache: "npm"

    - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0
          mongodb-replica-set: test-rs
        
    - run: npm ci

    - run: npm run build --if-present
      env: 
       DATABASE_URL=mongodb://localhost:27017/dev
    - run: npm run test:run 
